### ISSUE TITLE
Wrappers initialisation from full list of hyper-params 

### ISSUE THREAD

**Issue by blondered** [MobileTeleSystems/RecTools#157]
### Feature Description

Wrappers initialisation from full list of hyper-params (including wrapped)

### Why this feature?

- It will help us for save/load functions to models.
- It will help running experiment from configs (not supported in framework but often used by users)
- It will simplify code for experiments

### Additional context

Interface is not decided. Options are:

1. `model_factory` method that accepts smth like:
```
model_type: ials
model_params:
    fit_features_together: True
    implicit_factors: 32
    implicit_alpha: 10
```

2. accept params in `__init__`:
```
ials = ImplicitALSWrapperModel(fit_features_together=True, wrapped_params = {"factors: 32, alpha: 10"})
```
wrapped_params and initialised instance of wrapped model are both optional and user needs to pass one of them. If none is passed then default params are used.
